# Generated by Django 2.1.3 on 2018-12-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceRequestRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(max_length=30)),
                ('request_time', models.DateTimeField()),
                ('return_time', models.DateTimeField()),
                ('cost_time', models.IntegerField()),
                ('reponse_id', models.IntegerField()),
                ('message_length', models.IntegerField()),
            ],
        ),
    ]
