# Generated by Django 2.1.3 on 2018-12-11 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacerequestrecord',
            name='ip',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
