# Generated by Django 2.1.3 on 2018-12-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manage', '0002_interfacerequestrecord_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacerequestrecord',
            name='cost_time',
            field=models.IntegerField(verbose_name='花费时间'),
        ),
        migrations.AlterField(
            model_name='interfacerequestrecord',
            name='interface_name',
            field=models.CharField(max_length=30, verbose_name='接口名称'),
        ),
        migrations.AlterField(
            model_name='interfacerequestrecord',
            name='ip',
            field=models.CharField(max_length=30, verbose_name='ip地址'),
        ),
        migrations.AlterField(
            model_name='interfacerequestrecord',
            name='message_length',
            field=models.IntegerField(verbose_name='返回数据长度'),
        ),
        migrations.AlterField(
            model_name='interfacerequestrecord',
            name='reponse_id',
            field=models.IntegerField(verbose_name='返回http id'),
        ),
        migrations.AlterField(
            model_name='interfacerequestrecord',
            name='request_time',
            field=models.DateTimeField(verbose_name='请求时间'),
        ),
        migrations.AlterField(
            model_name='interfacerequestrecord',
            name='return_time',
            field=models.DateTimeField(verbose_name='返回时间'),
        ),
    ]
